image: barichello/godot-ci:4.3

variables:
  EXPORT_NAME: "luscinia"

stages:
  - test
  - export
  - deploy

test:
  stage: test
  tags:
    - docker 
  script:
    - godot -v --headless --script res://addons/gut/gut_cmdln.gd -gtest=res://Tests/Unit > test_output.log
  artifacts:
    name: "test-results"
    paths:
      - test_output.log
    when: always
  allow_failure: false



windows:
  stage: export
  tags:
    - docker 
  script:
    - mkdir -v -p build/windows
    - godot -v --headless --export-release "Windows Desktop" luscinia/project.godot ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: "$EXPORT_NAME-$CI_JOB_NAME"
    paths:
      - build/windows/
