image: barichello/godot-ci:4.3

variables:
  EXPORT_NAME: "luscinia"
  ANDROID_SDK_PATH: "/opt/android-sdk"
  

stages:
  - test
  - export
  - deploy

# test:
#   stage: test
#   tags:
#     - docker 
#   script:
#     - godot -v --headless --script res://luscinia/addons/gut/gut_cmdln.gd -gtest=res://luscinia/Tests/Unit > test_output.log
#   artifacts:
#     name: "test-results"
#     paths:
#       - test_output.log
#     when: always
#   allow_failure: false



windows:
  stage: export
  tags:
    - docker 
  script:
    - mkdir -v -p build/windows
    - godot -v --headless --export-release "Windows Desktop" luscinia/project.godot ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: "$EXPORT_NAME-$CI_JOB_NAME"
    paths:
      - build/windows/
    
android_debug:
  stage: export
  script:
    - mkdir -v -p build/android
    - EXPORT_DIR="$(readlink -f build)"
    - cd luscinia
    - godot --headless --verbose --export-debug "Android Debug" "$EXPORT_DIR/android/$EXPORT_NAME-debug.apk"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android

# Android Release Job. You will need to include keystore and password in the GitLab variable settings:
# 1. Take your generated keystore and convert it to Base64:
#   Linux & macOS: `base64 release.keystore -w 0`
#   Windows: `certutil -encodehex -f release.keystore encoded.txt 0x40000001`
# 2. Go to GitLab Project > Settings > CI/CD > Variables and copy the Base64-encoded keystore value in a new variable `SECRET_RELEASE_KEYSTORE_BASE64` as type variable.
# 3. Create a second variable SECRET_RELEASE_KEYSTORE_USER as type variable with the alias of your keystore as value.
# 4. Create a third variable SECRET_RELEASE_KEYSTORE_PASSWORD as type variable with the password of your keystore as value.
android:
  stage: export
  rules:
    - if: $SECRET_RELEASE_KEYSTORE_BASE64
    - if: $SECRET_RELEASE_KEYSTORE_USER
    - if: $SECRET_RELEASE_KEYSTORE_PASSWORD
  script:
    - echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/mygame.keystore
    - mkdir -v -p build/android
    - EXPORT_DIR="$(readlink -f build)"
    - cd luscinia
    - sed 's@keystore/release=".*"@keystore/release="'/root/mygame.keystore'"@g' -i export_presets.cfg
    - sed 's@keystore/release_user=".*"@keystore/release_user="'$SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
    - sed 's@keystore/release_password=".*"@keystore/release_password="'$SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
    - godot --headless --verbose --export-release "Android" $EXPORT_DIR/android/$EXPORT_NAME.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android
