image: barichello/godot-ci:4.3

variables:
  EXPORT_NAME: "luscinia"
  ANDROID_SDK_PATH: "C:/Users/jackp/AppData/Local/Android/Sdk"
  

stages:
  - test
  - export
  - deploy

# test:
#   stage: test
#   tags:
#     - docker 
#   script:
#     - godot -v --headless --script res://luscinia/addons/gut/gut_cmdln.gd -gtest=res://luscinia/Tests/Unit > test_output.log
#   artifacts:
#     name: "test-results"
#     paths:
#       - test_output.log
#     when: always
#   allow_failure: false



windows:
  stage: export
  tags:
    - docker 
  script:
    - mkdir -v -p build/windows
    - godot -v --headless --export-release "Windows Desktop" luscinia/project.godot ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: "$EXPORT_NAME-$CI_JOB_NAME"
    paths:
      - build/windows/
    

android:
  stage: export
  tags:
    - docker
  script:
    - mkdir -v -p build/android
    - export ANDROID_HOME=$ANDROID_SDK_PATH
    - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
    - godot -v --headless --export "Android" luscinia/project.godot ../build/android/$EXPORT_NAME.apk
  artifacts:
    name: "$EXPORT_NAME-android"
    paths:
      - build/android/ whats wrong with the sdk path