image: barichello/godot-ci:4.3

variables:
  EXPORT_NAME: "luscinia"
  ANDROID_SDK_PATH: "/opt/android-sdk"
  GODOT_ANDROID_KEYSTORE_RELEASE_PATH: ""  # Path to your release keystore
  GODOT_ANDROID_KEYSTORE_RELEASE_USER: ""  # Your keystore alias
  GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ""  # Your keystore password

stages:
  - test
  - export
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'


test:
  stage: test
  tags:
    - docker 
  script:
    - godot --headless --import --path ./luscinia
    - godot -v --headless --path ./luscinia -s addons/gut/gut_cmdln.gd -gdir=res://Tests/Unit -gexit > test_output.log
  artifacts:
    name: "test-results"
    paths:
      - test_output.log
    when: always
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH'


windows:
  stage: export
  tags:
    - docker 
  script:
    - mkdir -v -p build/windows
    - godot -v --headless --export-release "Windows Desktop" luscinia/project.godot ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: "$EXPORT_NAME-$CI_JOB_NAME"
    paths:
      - build/windows/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"
    
      
# android_debug:
#   stage: export
#   script:
#     - mkdir -v -p build/android
#     - EXPORT_DIR="$(readlink -f build)"
#     - cd luscinia
#     - godot --headless --verbose --export-debug "Android Debug" ../build/android/$EXPORT_NAME-debug.apk
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/android


android:
  stage: export
  rules:
    - if: $SECRET_RELEASE_KEYSTORE_BASE64
    - if: $SECRET_RELEASE_KEYSTORE_USER
    - if: $SECRET_RELEASE_KEYSTORE_PASSWORD
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    # Decode and create the keystore file
    - echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/mygame-release.keystore

    # Set the environment variables for the release keystore
    - export GODOT_ANDROID_KEYSTORE_RELEASE_PATH="/root/mygame-release.keystore"
    - export GODOT_ANDROID_KEYSTORE_RELEASE_USER="$SECRET_RELEASE_KEYSTORE_USER"
    - export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD="$SECRET_RELEASE_KEYSTORE_PASSWORD"

    # Build the Android APK (Release Version)
    - mkdir -v -p build/android
    - EXPORT_DIR="$(readlink -f build)"
    - cd luscinia
    - godot --headless --verbose --export-release "Android" ../build/android/$EXPORT_NAME.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android
  
